# deploy your software/project with Github actions
name: deploy-book

# O. I wanted to comment this out, because for now I want to push changes manually
# but there was an error on GitHub Actions, so I had to leave it 
  # Error: .github#L1
  # No event triggers defined in `on`

# only run this when the main branch changes
on: 
  push: 
    branches:
    - main 


#Sets permissions of the GITHUB-TOKEN to allow deployment to Pages
permissions: 
  contents: read
  pages: write
  id-token: write

# This job install dependencies. build the book, and pushes it to Pages
jobs:
  deploy-book:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      # O. I add this for java (from ChatGPT3.5), don't know if it's correct and works 
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17.0.0'
      

      - name: Install dependencies
        run: |
          pip install jupyter-book

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_build/html'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1